steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - simple-site
      - --source=.
      - --region=asia-northeast1
      - --platform=managed
      - --allow-unauthenticated
      - --update-env-vars=XLSX_FILE_ID=1DJpgUfh_YejgVgHRo-RRhMqONEGjqw8r
      - --project=$PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
